### ISSUE TITLE
about experiment for ScanObjectNN and ScanNet  dataset

### ISSUE THREAD

**Issue by amiltonwong** [raoyongming/PointGLR#1]
Hi, @raoyongming ,

Thanks for releasing the package. Besides the experiment for ModelNet40, could you also release the code for experiment for ScanObjectNN and ScanNet dataset (as mentioned in your paper)?

THX!

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work.

I have updated the code for experiments on ScanObjectNN and ScanNet.
