### ISSUE TITLE
I don't konw how to do next,it's strange, please answer me..

### ISSUE THREAD

**Issue by LJD877** [raoyongming/PointGLR#10]
![41119322e7e9dba648b6a44924f489a](https://user-images.githubusercontent.com/64898492/110199431-5538a500-7e93-11eb-9fbd-08358ec56278.png)

**Comment by raoyongming** [comment]
It seems you are using Windows to run the code. Our code is only tested on Linux. Some configurations may be different on Linux and Windows. I would recommend you to use our code on Linux :)
