### ISSUE TITLE
supervised vs. unsupervised

### ISSUE THREAD

**Issue by sheshap** [raoyongming/PointGLR#12]
Very inspiring work. Thanks for making the code available. 
Appreciate your efforts. 
I have a question in reference to results presented in Table 3 for RSCNN.

RSCNN original 92.9
RSCNN original with voting 93.6

RSCNN supervised (Large) 92.0
Your w/ RSCNN (Large) unsupervised 92.9

Why is RSCNN supervised (Large) less than RSCNN Original?

Also, please let us know separate steps for training the supervised and unsupervised versions.

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our paper.

One key observation in our paper is that larger networks may not always lead to better performance for supervised learning while our unsupervised learning method can more consistently improve performance when we enlarge the model (see Fig. 3).

Here we only provide the implementation of unsupervised learning. I think you can slightly modify the code by adding a classifier to train the supervised model. 

Best.
