### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by cuge1995** [raoyongming/PointGLR#6]
File "utils/pointnet2_utils.py", line 11, in <module>
    from _ext import pointnet2
  File "utils/_ext/pointnet2/__init__.py", line 3, in <module>
    from ._pointnet2 import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named '_ext.pointnet2._pointnet2'

when run '  CUDA_VISIBLE_DEVICES=0 python tools/prepare_modelnet.py '

my torch version is 0.4.1, python 3.6

**Comment by raoyongming** [comment]
I think you should first follow the step **Building C++/CUDA Extensions for PointNet++** to prepare the extensions. Since the C++/CUDA extension is adopted from RS-CNN, you can also refer to [this issue](https://github.com/Yochengliu/Relation-Shape-CNN/issues/27).

**Comment by cuge1995** [comment]
Thanks, this bug has been solved.
