### ISSUE TITLE
how to ensure that φ and Φ can map local and global features in the same feature space? 

### ISSUE THREAD

**Issue by HIKARI513** [raoyongming/PointGLR#7]
how to ensure that φ and Φ can map local and global features in the same feature space? in this paper, I only see the loss_(L2G), but I highly doubt that it's enough to map those two things in th same space, as author says, the shared feature space?  Am I missing sth or can anyone help me?

**Comment by raoyongming** [comment]
Thanks for your interest in our work.

The term "shared feature space" here means that we want to map the local and global features to the same 512-dim hypersphere as shown in Figure 2. Feature space usually refers to the 𝑛-dimensions where the variables live (see [the slides](http://www2.ece.ohio-state.edu/~aleix/FeatureExtraction.pdf)). Our basic idea is to map the two features into the same dimension such that we can measure the similarity of them, so the distributions of these two kinds of features may not be strictly aligned after mapping.
