### ISSUE TITLE
How to train on RSCNN model?

### ISSUE THREAD

**Issue by mtli77** [raoyongming/PointGLR#8]
Hi, @raoyongming 
Thank you for sharing!

You just list the options on pointnet2 training :
```
bash train.sh exp_name pointnet2 modelnet
``` 
But you did not specify the `--arch` config of training on RSCNN? What is the name of RSCNN in your code?

Thank you very much!

**Comment by raoyongming** [comment]
Thanks for your interest in our paper.

The name of RSCNN is `rscnn`.
