### ISSUE TITLE
The meaning of a variable in code

### ISSUE THREAD

**Issue by YAOMOREN** [raoyongming/PointGLR#9]
I don't understand what the features1, fuse_global, global_feature1, REFs1 stand for in the code, especially fuse_global, global_feature1.Can you explain that to help me understand the paper better

**Comment by raoyongming** [comment]
Sorry for the late response.

`feature1` is the list of features from different abstraction levels
`fuse_global ` is the summarized global feature (see f in Eq.7 in our paper)
`global_feature1 ` is the global feature of the last abstraction level
`REFs1 ` is the list of features from the first two abstraction levels (local features)

The definition of these variables can be found [here](https://github.com/raoyongming/PointGLR/blob/6ca16d9db197317c03758f1f048a4f40c1201b02/models/pointnet2_ss.py#L176).
